services:
  zookeeper:
    image: zookeeper:3.7.2
    ports:
      - "2181:2181"
  
  kafka:
    image: ubuntu/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ppe_detection
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src:/scripts  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      - kafka
      - db
    volumes:
      - ./data:/app/data
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=ppe_detection
    command: ["python", "src/utils/kafka_consumer.py"]

  websocket-server:
    build: .
    command: ["python", "src/utils/websocket_server.py"]
    ports:
      - "3001:3001"
    depends_on:
      - app

volumes:
  pgdata:


